services:
  - type: web
    name: bhinsearch-backend
    env: python
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.12"
      - key: DATABASE_NAME
        value: bhinsearch_db
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: API_V1_PREFIX
        value: /api/v1
      - key: PROJECT_NAME
        value: 보험업계 ATS API
      - key: UPLOAD_DIR
        value: ./uploads
      - key: MAX_FILE_SIZE
        value: "10485760"
      - key: ALLOWED_ORIGINS
        value: '["https://jewook-an.github.io","http://localhost:3000"]'
      - key: GOOGLE_CLIENT_ID
        value: 36041664943-83vrbe08pdalj9r22b12jvr1t7fminj7.apps.googleusercontent.com
      - key: MONGODB_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
